# -*- mode: ruby -*-
# vi: set ft=ruby :
#
#Define the list of machines
cluster = {
	:controller => {
		:hostname => "controller",
		:ipaddress => "192.168.56.100",
		:cpus => "2",
		:memory => "512"
	},
	:node1 => {
		:hostname => "node1",
		:ipaddress => "192.168.56.101",
		:cpus => "1",
		:memory => "512",
	},
	:node2 => {
		:hostname => "node2",
		:ipaddress => "192.168.56.102",
		:cpus => "1",
		:memory => "1024"
	}
}

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |global|
	cluster.each_pair do |name,options|
		global.vm.define name do |node|
			#per VM customizations
			node.vm.box = "ubuntu/jammy64"
			node.vm.hostname = "#{name}"
			node.vm.network :private_network, ip: options[:ipaddress]
			node.vm.provider :virtualbox do |v|
				#v.customize ["modifyvm", :id, "--memory", option[:memory]]
				v.cpus = options[:cpus]
				v.memory = options[:memory]
			end
			node.vm.provision "shell", path: "./scripts/slurm-bootstrap.sh"
			node.vm.provision "shell", reboot: true
		end
	end
end
